"""Export routines for prototype outputs and audit-oriented artefacts.

This module consolidates the outputs produced by the prototype into simple CSV
files that can be inspected outside the application. The exported artefacts are
designed to support traceability: a dataset snapshot is preserved, detected
issues are listed explicitly, and review decisions are written to a separate
log for audit-style inspection.
"""

import logging
from pathlib import Path

import pandas as pd

LOGGER = logging.getLogger(__name__)


def export_outputs(
    dataframe: pd.DataFrame,
    validation_results: dict,
    anomaly_results: pd.DataFrame,
    review_log: pd.DataFrame,
    output_dir: str | Path,
) -> dict:
    """Export the prototype outputs to CSV files on disk.

    Parameters
    ----------
    dataframe : pandas.DataFrame
        Loaded VAT dataset that should be written to a snapshot export without
        altering the underlying record values.
    validation_results : dict
        Structured validation output containing issue records.
    anomaly_results : pandas.DataFrame
        Ranked anomaly records produced by the anomaly detection stage.
    review_log : pandas.DataFrame
        Review decisions generated by the simulated human review stage.
    output_dir : str or pathlib.Path
        Directory into which the CSV artefacts should be written.

    Returns
    -------
    dict
        Mapping from export label to generated file path.

    Notes
    -----
    The exporter keeps outputs separate so the prototype can demonstrate both
    operational convenience and auditability. The dataset snapshot, issue
    report, and review log serve distinct purposes in a research evaluation
    setting.
    """
    LOGGER.info("Exporting dataset snapshot and reporting artefacts to %s", output_dir)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    dataset_snapshot_path = output_path / "dataset_snapshot.csv"
    issue_report_path = output_path / "issue_report.csv"
    review_log_path = output_path / "review_log.csv"

    # The dataset export preserves the loaded data so findings remain advisory.
    dataframe.to_csv(dataset_snapshot_path, index=False)

    issue_rows = pd.DataFrame(validation_results["issues"])
    if not anomaly_results.empty:
        anomaly_issue_rows = anomaly_results.copy()
        anomaly_issue_rows["issue_type"] = "anomaly"
        anomaly_issue_rows["column"] = "net_amount"
        anomaly_issue_rows["message"] = anomaly_issue_rows["reason"]
        issue_rows = pd.concat([issue_rows, anomaly_issue_rows], ignore_index=True, sort=False)

    # Writing issue and review outputs separately makes the review trail explicit.
    issue_rows.to_csv(issue_report_path, index=False)
    review_log.to_csv(review_log_path, index=False)
    LOGGER.debug(
        "Exported files created: %s, %s, %s",
        dataset_snapshot_path,
        issue_report_path,
        review_log_path,
    )

    return {
        "dataset_snapshot": dataset_snapshot_path,
        "issue_report": issue_report_path,
        "review_log": review_log_path,
    }
